import Header from '@/components/Header/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import { ReactQueryProvider } from './reactQueryProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Películas y series',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <ReactQueryProvider>
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  )
}
