GET http://localhost:3001/favs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTYyNDU1M2MwNTRmMDM0YTNmNWM4ZCIsImlhdCI6MTY4NzgwOTU4MCwiZXhwIjoxNjg3ODk1OTgwfQ.Ab1MHlkij3SnOelHNRFqJgvGeOLK7_Jv-M0OqFsURMM

{
   "data":{
    "poster_path":"dsadsad", 
    "id": "dsadas", 
    "title": "dadsa", 
    "vote_average": 1232312 
    },
   "path": "dadsadas"
}