GET http://localhost:3001/favs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTYyNDU1M2MwNTRmMDM0YTNmNWM4ZCIsImlhdCI6MTY4Nzg5OTE4OCwiZXhwIjoxNjg3OTg1NTg4fQ.65N3ep6uzbwTe-GS5CjpKoYpicIokDcdTFMDKND-t_M

{
   "data":{
    "poster_path":"dsadsad", 
    "id": "dsadas", 
    "title": "dadsa", 
    "vote_average": 1232312 
    },
   "path": "dadsadas"
}